added ci file

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,6 +1,202 @@
 name: Node.js CI
 
 on:
-  workflow_dispatch: 
+  push:
+    branches: [ main ]
+  pull_request:
+    branches: [ main ]
+  
+permissions:
+  contents: write # required to push to cd repository with github_token or PAT
+
+env:
+  IMAGE_TAG: ${{ github.sha }} #
+
+jobs:
+  compile:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up Node.js 
+        uses: actions/steup-node@v4
+        with:
+          node-version: '23' 
+
+      - name: Frontend-Complilation (Syntax-Check)
+        run: |
+          cd client
+          find . -name "*.js" -exec node --check {} +      
+
+
+      - name: Backend-Complilation (Syntax-Check)
+        run: |
+          cd api
+          find . -name "*.js" -exec node --check {} +
+
+  gitleaks-scan:  #job to scan for secrets in the codebase using gitleaks
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Gitleaks setup
+        uses: gitleaks/gitleaks-action@v2
+
+      - name: Gitleaks scan
+        run: |
+          gitleaks detect --source  ./client --exit-code 1
+          gitleaks detect --source ./api --exit-code 1
+
+  trivy-fs-scan:
+    runs-on: ubuntu-latest
+    needs: gitleaks-scan
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Run Trivy vulnerability scannner (FS)
+        uses: aquasecurity/trivy-action@0.28.0
+        with:
+          scan-type: fs
+          scan-ref: .
+          format: table
+          ignore-unfixed: false
+          vuln-type: os,library
+          severity: CRITICAL,HIGH
+
+  build_backend_docker_image_and_push:
+    runs-on: ubuntu-latest
+    needs: trivy-fs-scan
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Login DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Build and push Docker image (Backend)
+        uses: docker/build-push-action@v6
+        with:
+          content: ./api
+          file: ./api/Dockerfile
+          push: true
+          tags: |
+            akashshinde/backend:latest
+            akashshinde/backend:${{ env.IMAGE_TAG }}
+
+  build_frontend_docker_image_and_push:
+    runs-on: ubuntu-latest
+    needs: trivy-fs-scan
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Login DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Build and push Docker image (Frontend)
+        uses: docker/build-push-action@v6
+        with:
+          content: ./client
+          file: ./client/Dockerfile
+          push: true
+          tags: |
+            akashshinde/frontend:latest
+            akashshinde/frontend:${{ env.IMAGE_TAG }}
+
+  trivy-image-scan:
+    runs-on: ubuntu-latest   
+    needs:
+      - build_backend_docker_image_and_push
+      - build_frontend_docker_image_and_push
+    steps:
+      - name: Run trivy image scan for backend
+        uses: aquasecurity/trivy-action@0.28.0
+        with:
+          scan-type: image   
+          image_ref: akashshinde/backend:${{ env.IMAGE_TAG }}  
+          format: table
+          exit-code: '1'
+          ignore-unfixed: false
+          vuln-type: os,librabry
+          severity: CRITICAL,HIGH
+
+      - name: Run trivy image scan for frontend
+        uses: aquasecurity/trivy-action@0.28.0
+        with:
+          scan-type: image   
+          image_ref: akashshinde/frontend:${{ env.IMAGE_TAG }}  
+          format: table
+          exit-code: '1' 
+          ignore-unfixed: false
+          vuln-type: os,librabry
+          severity: CRITICAL,HIGH
+
+  update_cd_repository:
+    runs-on: ubutu-latest
+    needs: trivy-image-scan
+    steps:
+      - name: Checkout CD repository
+        uses: actions/checkout@v4
+        with:
+          repository: akashshinde/docker-kubernetes-cd
+          ref: main
+          token: ${{ secrets.CD_REPO_TOKEN }}
+          path: cd 
+
+      - name: Bump images in manifest files
+        working-directory: cd
+        env: 
+          IMAGE_TAG: ${{ env.IMAGE_TAG }}
+        run: |
+          curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o yq && sudo install yq /usr/local/bin/yq
     
-    
+          # -- Safely cleanup: Remove any accidental .spec.template from service docs
+          yq -i '(. | select(.kind=="Service")) |= del(.spec.template)' k8s-prod/backend.yaml
+          yq -i '(. | select(.kind=="Service")) |= del(.spec.template)' k8s-prod/frontend.yaml
+
+          # -- Update only Deployment images (backend)
+          yq -i '
+            (. | select(.kind=="Deployment")
+               | .spec.template.spec.containers[]
+               | select(.name=="backend")
+               | .image)
+            = "akashshinde/backend:" + strenv(IMAGE_TAG)
+          ' k8s-prod/backend.yaml
+
+
+          # -- Update only Deployment images (frontend)
+          yq -i '
+            (. | select(.kind=="Deployment")
+               | .spec.template.spec.containers[]
+               | select(.name=="frontend")
+               | .image)
+            = "akashshinde/frontend:" + strenv(IMAGE_TAG) 
+          ' k8s-prod/frontend.yaml
+
+          # -- Commit and push to cd repository
+          working-directory: cd
+          run: |
+            git config user.name "ci-bot"
+            git config user.email "ci-bot@users.noreply.github.com"
+            git add -A
+            git commit -m "bump images to ${IMAGE_TAG}" || echo "no changes"
+            git push
